## Basic Configuration
baseurl = "https://yf-gooo.github.io/"
languageCode = "zh"

title = "YF-Blog"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

summarylength = 50

paginate = 10

## Site Settings
[params]
    author = "Yifan"
    title = "Title"
    description = "一个缓慢成长中的数据科学犬"
    authorimage = "/img/dog.jpeg"
    dateformat = "Jan 2, 2006"

    # sidebar, copyright & license
    copyright = "htr3n"
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = false

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    github = "https://github.com/YF-Gooo"
    linkedin = "<username>"
    email = "your-email@example.com"
    # gravatar = "your-email@example.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 200
    url = "/portfolio/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
